<assemblies timestamp="11/23/2024 15:14:03">
  <assembly name="/projects/challenge/HRBackendExercise.API.Tests/bin/Debug/net6.0/HRBackendExercise.API.Tests.dll" run-date="2024-11-23" run-time="15:14:03" total="47" passed="10" failed="37" skipped="0" time="3.345" errors="0">
    <errors />
    <collection total="1" passed="1" failed="0" skipped="0" name="Test collection for HRBackendExercise.API.Tests.Basic.Controller_DeleteShould" time="0.010">
      <test name="ControllerDeleteShouldReturnSuccessStatusCode" type="HRBackendExercise.API.Tests.Basic.Controller_DeleteShould" method="ReturnSuccessStatusCode" time="0.0097140" result="Pass">
        <traits />
      </test>
    </collection>
    <collection total="1" passed="1" failed="0" skipped="0" name="Test collection for HRBackendExercise.API.Tests.Basic.Controller_GetShould" time="0.299">
      <test name="ControllerGetShouldReturnOk" type="HRBackendExercise.API.Tests.Basic.Controller_GetShould" method="ReturnOk_OnNotNullProduct" time="0.2990728" result="Pass">
        <traits />
      </test>
    </collection>
    <collection total="2" passed="2" failed="0" skipped="0" name="Test collection for HRBackendExercise.API.Tests.Basic.Controller_PostShould" time="0.005">
      <test name="ControllerPostShouldReturnBadRequestOnNullInput" type="HRBackendExercise.API.Tests.Basic.Controller_PostShould" method="ReturnBadRequest_OnNullInputProduct" time="0.0012308" result="Pass">
        <traits />
      </test>
      <test name="ControllerPostShouldReturnSuccessStatusCode" type="HRBackendExercise.API.Tests.Basic.Controller_PostShould" method="ReturnSuccessStatusCode" time="0.0036756" result="Pass">
        <traits />
      </test>
    </collection>
    <collection total="2" passed="2" failed="0" skipped="0" name="Test collection for HRBackendExercise.API.Tests.Basic.Controller_PutShould" time="0.181">
      <test name="ControllerPutShouldReturnSuccessStatusCode" type="HRBackendExercise.API.Tests.Basic.Controller_PutShould" method="ReturnSuccessStatusCode" time="0.1810372" result="Pass">
        <traits />
      </test>
      <test name="ControllerPutShouldReturnBadRequestOnNullProduct" type="HRBackendExercise.API.Tests.Basic.Controller_PutShould" method="ReturnBadRequest_OnNullInputProduct" time="0.0002746" result="Pass">
        <traits />
      </test>
    </collection>
    <collection total="1" passed="0" failed="1" skipped="0" name="Test collection for HRBackendExercise.API.Tests.Basic.Service_CreateShould" time="0.000">
      <test name="ServiceCreateShouldReturnNotNull" type="HRBackendExercise.API.Tests.Basic.Service_CreateShould" method="ReturnNotNull" time="0.0004664" result="Fail">
        <failure>
          <message>System.ArgumentNullException : Value cannot be null. (Parameter 'source')</message>
          <stack-trace>   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at HRBackendExercise.API.Services.ProductService.Create(Product entity) in /projects/challenge/HRBackendExercise.API/Services/ProductService.cs:line 12
   at HRBackendExercise.API.Tests.Basic.Service_CreateShould.ReturnNotNull() in /projects/challenge/HRBackendExercise.API.Tests/Basic/ServiceBasicTests.cs:line 18</stack-trace>
        </failure>
        <traits />
      </test>
    </collection>
    <collection total="2" passed="0" failed="2" skipped="0" name="Test collection for HRBackendExercise.API.Tests.Basic.Service_DeleteShould" time="0.008">
      <test name="ServiceDeleteShouldRemoveProudct" type="HRBackendExercise.API.Tests.Basic.Service_DeleteShould" method="RemoveProduct" time="0.0059879" result="Fail">
        <failure>
          <message>System.ArgumentNullException : Value cannot be null. (Parameter 'source')</message>
          <stack-trace>   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at HRBackendExercise.API.Services.ProductService.Create(Product entity) in /projects/challenge/HRBackendExercise.API/Services/ProductService.cs:line 12
   at HRBackendExercise.API.Tests.Basic.Service_DeleteShould.RemoveProduct() in /projects/challenge/HRBackendExercise.API.Tests/Basic/ServiceBasicTests.cs:line 130</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ServiceDeleteShouldDoNothing" type="HRBackendExercise.API.Tests.Basic.Service_DeleteShould" method="DoNothing_OnCollectionNotContainsProduct" time="0.0015338" result="Fail">
        <failure>
          <message>System.ArgumentNullException : Value cannot be null. (Parameter 'source')</message>
          <stack-trace>   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at HRBackendExercise.API.Services.ProductService.Create(Product entity) in /projects/challenge/HRBackendExercise.API/Services/ProductService.cs:line 12
   at HRBackendExercise.API.Tests.Basic.Service_DeleteShould.DoNothing_OnCollectionNotContainsProduct() in /projects/challenge/HRBackendExercise.API.Tests/Basic/ServiceBasicTests.cs:line 146</stack-trace>
        </failure>
        <traits />
      </test>
    </collection>
    <collection total="2" passed="0" failed="2" skipped="0" name="Test collection for HRBackendExercise.API.Tests.Basic.Service_GetAllShould" time="0.012">
      <test name="ServiceGetAllShouldReturnEmptyCollection" type="HRBackendExercise.API.Tests.Basic.Service_GetAllShould" method="RetrunEmpty" time="0.0009187" result="Fail">
        <failure>
          <message>System.ArgumentNullException : Value cannot be null. (Parameter 'collection')</message>
          <stack-trace>   at HRBackendExercise.API.Tests.Basic.Service_GetAllShould.RetrunEmpty() in /projects/challenge/HRBackendExercise.API.Tests/Basic/ServiceBasicTests.cs:line 54</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ServiceGetAllShouldAllEntries" type="HRBackendExercise.API.Tests.Basic.Service_GetAllShould" method="ReturnAllEntries" time="0.0113862" result="Fail">
        <failure>
          <message>System.ArgumentNullException : Value cannot be null. (Parameter 'source')</message>
          <stack-trace>   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at HRBackendExercise.API.Services.ProductService.Create(Product entity) in /projects/challenge/HRBackendExercise.API/Services/ProductService.cs:line 12
   at HRBackendExercise.API.Tests.Basic.Service_GetAllShould.ReturnAllEntries() in /projects/challenge/HRBackendExercise.API.Tests/Basic/ServiceBasicTests.cs:line 64</stack-trace>
        </failure>
        <traits />
      </test>
    </collection>
    <collection total="1" passed="0" failed="1" skipped="0" name="Test collection for HRBackendExercise.API.Tests.Basic.Service_GetShould" time="0.001">
      <test name="ServiceGetShouldReturnNotNull" type="HRBackendExercise.API.Tests.Basic.Service_GetShould" method="ReturnNotNull_OnValidId" time="0.0005350" result="Fail">
        <failure>
          <message>System.ArgumentNullException : Value cannot be null. (Parameter 'source')</message>
          <stack-trace>   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at HRBackendExercise.API.Services.ProductService.Create(Product entity) in /projects/challenge/HRBackendExercise.API/Services/ProductService.cs:line 12
   at HRBackendExercise.API.Tests.Basic.Service_GetShould.ReturnNotNull_OnValidId() in /projects/challenge/HRBackendExercise.API.Tests/Basic/ServiceBasicTests.cs:line 34</stack-trace>
        </failure>
        <traits />
      </test>
    </collection>
    <collection total="2" passed="0" failed="2" skipped="0" name="Test collection for HRBackendExercise.API.Tests.Basic.Service_UpdateShould" time="0.010">
      <test name="ServiceUpdateShouldThrowException" type="HRBackendExercise.API.Tests.Basic.Service_UpdateShould" method="ThrowException_OnInvalidId" time="0.0086656" result="Fail">
        <failure>
          <message>Assert.StartsWith() Failure: String start does not match
String:         "Value cannot be null. (Parameter 'source'"···
Expected start: "Invalid entity."</message>
          <stack-trace>   at HRBackendExercise.API.Tests.Basic.Service_UpdateShould.ThrowException_OnInvalidId() in /projects/challenge/HRBackendExercise.API.Tests/Basic/ServiceBasicTests.cs:line 117</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ServiceUpdateShouldUpdateValues" type="HRBackendExercise.API.Tests.Basic.Service_UpdateShould" method="UpdateValues" time="0.0011822" result="Fail">
        <failure>
          <message>System.ArgumentNullException : Value cannot be null. (Parameter 'source')</message>
          <stack-trace>   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at HRBackendExercise.API.Services.ProductService.Create(Product entity) in /projects/challenge/HRBackendExercise.API/Services/ProductService.cs:line 12
   at HRBackendExercise.API.Tests.Basic.Service_UpdateShould.UpdateValues() in /projects/challenge/HRBackendExercise.API.Tests/Basic/ServiceBasicTests.cs:line 93</stack-trace>
        </failure>
        <traits />
      </test>
    </collection>
    <collection total="27" passed="4" failed="23" skipped="0" name="Test collection for HRBackendExercise.API.Tests.Hidden.ControllerTests" time="0.186">
      <test name="ControllerPostShouldReturnBadRequestOnNullSKU" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Post_ShouldReturnBadRequest_OnNullSKU" time="0.0097032" result="Fail">
        <failure>
          <message>Assert.IsType() Failure: Value is not the exact type
Expected: typeof(Microsoft.AspNetCore.Mvc.BadRequestResult)
Actual:   typeof(Microsoft.AspNetCore.Mvc.OkObjectResult)</message>
          <stack-trace>   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Post_ShouldReturnBadRequest_OnNullSKU() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 202</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerGetShouldReturnNotFound" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Get_ShouldReturnNotFound_OnNullProduct" time="0.0035331" result="Fail">
        <failure>
          <message>Assert.IsType() Failure: Value is not the exact type
Expected: typeof(Microsoft.AspNetCore.Mvc.NotFoundResult)
Actual:   typeof(Microsoft.AspNetCore.Mvc.OkObjectResult)</message>
          <stack-trace>   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Get_ShouldReturnNotFound_OnNullProduct() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 77</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerPutShouldReturnNotFound" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Put_ShouldReturnNotFound_OnNullProduct" time="0.0013012" result="Fail">
        <failure>
          <message>Assert.IsType() Failure: Value is not the exact type
Expected: typeof(Microsoft.AspNetCore.Mvc.NotFoundResult)
Actual:   typeof(Microsoft.AspNetCore.Mvc.OkResult)</message>
          <stack-trace>   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Put_ShouldReturnNotFound_OnNullProduct() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 309</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerPutInternalServerErrorShouldHaveMessageProp" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Put_ResponseShouldHasMessageProperty_OnInternalServerErrorScenario" time="0.0101657" result="Fail">
        <failure>
          <message>System.Exception : This is my dummy exception.</message>
          <stack-trace>   at Moq.Behaviors.ThrowException.Execute(Invocation invocation) in /_/src/Moq/Behaviors/ThrowException.cs:line 64
   at Moq.MethodCall.ExecuteCore(Invocation invocation) in /_/src/Moq/MethodCall.cs:line 230
   at Moq.Setup.Execute(Invocation invocation) in /_/src/Moq/Setup.cs:line 144
   at Moq.FindAndExecuteMatchingSetup.Handle(Invocation invocation, Mock mock) in /_/src/Moq/Interception/InterceptionAspects.cs:line 263
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation) in /_/src/Moq/Interception/Mock.cs:line 17
   at Moq.CastleProxyFactory.Interceptor.Intercept(IInvocation underlying) in /_/src/Moq/Interception/CastleProxyFactory.cs:line 218
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IProductsServiceProxy.Update(Product entity)
   at HRBackendExercise.API.Controllers.ProductsController.Put(Product product) in /projects/challenge/HRBackendExercise.API/Controllers/ProductsController.cs:line 48
   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Put_ResponseShouldHasMessageProperty_OnInternalServerErrorScenario() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 254</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerPostShouldImplementService" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Post_ShouldCallCreateFromService" time="0.0197699" result="Pass">
        <traits />
      </test>
      <test name="ControllerPostShouldReturnCreated" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Post_ShouldReturnCreatedStatusCode" time="0.0014617" result="Fail">
        <failure>
          <message>Assert.IsType() Failure: Value is not the exact type
Expected: typeof(Microsoft.AspNetCore.Mvc.ObjectResult)
Actual:   typeof(Microsoft.AspNetCore.Mvc.OkObjectResult)</message>
          <stack-trace>   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Post_ShouldReturnCreatedStatusCode() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 166</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerPostShouldBeHttpDecorated" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Post_ShouldHasAccordinglyDecorator" time="0.0135703" result="Fail">
        <failure>
          <message>Assert.Contains() Failure: Filter not matched in collection
Collection: []</message>
          <stack-trace>   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Post_ShouldHasAccordinglyDecorator() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 148</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerPostShouldReturnBadRequestOnZeroPrice" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Post_ShouldReturnBadRequest_OnPriceEqualsToZero" time="0.0007435" result="Fail">
        <failure>
          <message>Assert.IsType() Failure: Value is not the exact type
Expected: typeof(Microsoft.AspNetCore.Mvc.BadRequestResult)
Actual:   typeof(Microsoft.AspNetCore.Mvc.OkObjectResult)</message>
          <stack-trace>   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Post_ShouldReturnBadRequest_OnPriceEqualsToZero() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 217</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerDeleteShouldReturnNoContent" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Delete_ShouldReturnNoContent" time="0.0099097" result="Pass">
        <traits />
      </test>
      <test name="ControllerPutShouldReturnNoContent" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Put_ShouldReturnNoContent" time="0.0030322" result="Fail">
        <failure>
          <message>Assert.Equal() Failure: Values differ
Expected: 204
Actual:   200</message>
          <stack-trace>   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Put_ShouldReturnNoContent() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 291</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerDeleteShouldBeHttpDecorated" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Delete_ShouldHasAccordinglyDecorator" time="0.0006058" result="Fail">
        <failure>
          <message>Assert.Contains() Failure: Filter not matched in collection
Collection: []</message>
          <stack-trace>   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Delete_ShouldHasAccordinglyDecorator() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 433</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerGetShouldImplementService" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Get_ShouldCallGetByIdFromService" time="0.0020114" result="Pass">
        <traits />
      </test>
      <test name="ControllerDeleteShouldImplementService" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Delete_ShouldCallDeleteFromService" time="0.0124987" result="Pass">
        <traits />
      </test>
      <test name="ControllerDeleteInternalServerErrorShouldHaveMessageProp" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Delete_ResponseShouldHasMessageProperty_OnInternalServerErrorScenario" time="0.0019173" result="Fail">
        <failure>
          <message>System.Exception : This is my dummy exception</message>
          <stack-trace>   at Moq.Behaviors.ThrowException.Execute(Invocation invocation) in /_/src/Moq/Behaviors/ThrowException.cs:line 64
   at Moq.MethodCall.ExecuteCore(Invocation invocation) in /_/src/Moq/MethodCall.cs:line 230
   at Moq.Setup.Execute(Invocation invocation) in /_/src/Moq/Setup.cs:line 144
   at Moq.FindAndExecuteMatchingSetup.Handle(Invocation invocation, Mock mock) in /_/src/Moq/Interception/InterceptionAspects.cs:line 263
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation) in /_/src/Moq/Interception/Mock.cs:line 17
   at Moq.CastleProxyFactory.Interceptor.Intercept(IInvocation underlying) in /_/src/Moq/Interception/CastleProxyFactory.cs:line 218
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IProductsServiceProxy.GetById(Int32 id)
   at HRBackendExercise.API.Controllers.ProductsController.Delete(Int32 id) in /projects/challenge/HRBackendExercise.API/Controllers/ProductsController.cs:line 55
   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Delete_ResponseShouldHasMessageProperty_OnInternalServerErrorScenario() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 415</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerPutShouldReturnBadRequestOnZeroId" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Put_ShouldReturnBadRequest_OnIdEqualsToZero" time="0.0006814" result="Fail">
        <failure>
          <message>Assert.IsType() Failure: Value is not the exact type
Expected: typeof(Microsoft.AspNetCore.Mvc.BadRequestResult)
Actual:   typeof(Microsoft.AspNetCore.Mvc.OkResult)</message>
          <stack-trace>   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Put_ShouldReturnBadRequest_OnIdEqualsToZero() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 377</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerDeleteShouldReturnNotFound" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Delete_ShouldReturnNotFound_OnNullProduct" time="0.0076767" result="Fail">
        <failure>
          <message>System.Exception : This is my dummy exception</message>
          <stack-trace>   at Moq.Behaviors.ThrowException.Execute(Invocation invocation) in /_/src/Moq/Behaviors/ThrowException.cs:line 64
   at Moq.MethodCall.ExecuteCore(Invocation invocation) in /_/src/Moq/MethodCall.cs:line 230
   at Moq.Setup.Execute(Invocation invocation) in /_/src/Moq/Setup.cs:line 144
   at Moq.FindAndExecuteMatchingSetup.Handle(Invocation invocation, Mock mock) in /_/src/Moq/Interception/InterceptionAspects.cs:line 263
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation) in /_/src/Moq/Interception/Mock.cs:line 17
   at Moq.CastleProxyFactory.Interceptor.Intercept(IInvocation underlying) in /_/src/Moq/Interception/CastleProxyFactory.cs:line 218
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IProductsServiceProxy.Delete(Product entity)
   at HRBackendExercise.API.Controllers.ProductsController.Delete(Int32 id) in /projects/challenge/HRBackendExercise.API/Controllers/ProductsController.cs:line 56
   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Delete_ShouldReturnNotFound_OnNullProduct() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 470</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerGetInternalServerErrorShouldHaveMessageProp" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Get_ResponseShouldHasMessageProperty_OnInternalServerErrorScenario" time="0.0014964" result="Fail">
        <failure>
          <message>System.Exception : This is my dummy exception</message>
          <stack-trace>   at Moq.Behaviors.ThrowException.Execute(Invocation invocation) in /_/src/Moq/Behaviors/ThrowException.cs:line 64
   at Moq.MethodCall.ExecuteCore(Invocation invocation) in /_/src/Moq/MethodCall.cs:line 230
   at Moq.Setup.Execute(Invocation invocation) in /_/src/Moq/Setup.cs:line 144
   at Moq.FindAndExecuteMatchingSetup.Handle(Invocation invocation, Mock mock) in /_/src/Moq/Interception/InterceptionAspects.cs:line 263
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation) in /_/src/Moq/Interception/Mock.cs:line 17
   at Moq.CastleProxyFactory.Interceptor.Intercept(IInvocation underlying) in /_/src/Moq/Interception/CastleProxyFactory.cs:line 218
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IProductsServiceProxy.GetById(Int32 id)
   at HRBackendExercise.API.Controllers.ProductsController.Get(Int32 id) in /projects/challenge/HRBackendExercise.API/Controllers/ProductsController.cs:line 20
   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Get_ResponseShouldHasMessageProperty_OnInternalServerErrorScenario() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 41</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerDeleteShouldReturnInternalServerError" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Delete_ShouldReturnInternalServerError_OnUnhandledException" time="0.0018495" result="Fail">
        <failure>
          <message>System.Exception : This is my dummy exception</message>
          <stack-trace>   at Moq.Behaviors.ThrowException.Execute(Invocation invocation) in /_/src/Moq/Behaviors/ThrowException.cs:line 64
   at Moq.MethodCall.ExecuteCore(Invocation invocation) in /_/src/Moq/MethodCall.cs:line 230
   at Moq.Setup.Execute(Invocation invocation) in /_/src/Moq/Setup.cs:line 144
   at Moq.FindAndExecuteMatchingSetup.Handle(Invocation invocation, Mock mock) in /_/src/Moq/Interception/InterceptionAspects.cs:line 263
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation) in /_/src/Moq/Interception/Mock.cs:line 17
   at Moq.CastleProxyFactory.Interceptor.Intercept(IInvocation underlying) in /_/src/Moq/Interception/CastleProxyFactory.cs:line 218
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IProductsServiceProxy.GetById(Int32 id)
   at HRBackendExercise.API.Controllers.ProductsController.Delete(Int32 id) in /projects/challenge/HRBackendExercise.API/Controllers/ProductsController.cs:line 55
   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Delete_ShouldReturnInternalServerError_OnUnhandledException() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 491</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerPutShouldImplementService" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Put_ShouldCallUpdateFromService" time="0.0592088" result="Fail">
        <failure>
          <message>Moq.MockException : 
Expected invocation on the mock once, but was 0 times: x =&gt; x.GetById(12)

Performed invocations:

   Mock&lt;IProductsService:23&gt; (x):

      IProductsService.Update(Product)
</message>
          <stack-trace>   at Moq.Mock.Verify(Mock mock, LambdaExpression expression, Times times, String failMessage) in /_/src/Moq/Mock.cs:line 331
   at Moq.Mock`1.Verify[TResult](Expression`1 expression, Func`1 times) in /_/src/Moq/Mock`1.cs:line 1033
   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Put_ShouldCallUpdateFromService() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 235</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerPostInternalServerErrorShouldHaveMessageProp" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Post_ResponseShouldHasMessageProperty_OnInternalServerErrorScenario" time="0.0016977" result="Fail">
        <failure>
          <message>System.Exception : This is my dummy exception</message>
          <stack-trace>   at Moq.Behaviors.ThrowException.Execute(Invocation invocation) in /_/src/Moq/Behaviors/ThrowException.cs:line 64
   at Moq.MethodCall.ExecuteCore(Invocation invocation) in /_/src/Moq/MethodCall.cs:line 230
   at Moq.Setup.Execute(Invocation invocation) in /_/src/Moq/Setup.cs:line 144
   at Moq.FindAndExecuteMatchingSetup.Handle(Invocation invocation, Mock mock) in /_/src/Moq/Interception/InterceptionAspects.cs:line 263
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation) in /_/src/Moq/Interception/Mock.cs:line 17
   at Moq.CastleProxyFactory.Interceptor.Intercept(IInvocation underlying) in /_/src/Moq/Interception/CastleProxyFactory.cs:line 218
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IProductsServiceProxy.Create(Product entity)
   at HRBackendExercise.API.Controllers.ProductsController.Post(Product product) in /projects/challenge/HRBackendExercise.API/Controllers/ProductsController.cs:line 37
   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Post_ResponseShouldHasMessageProperty_OnInternalServerErrorScenario() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 130</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerPutShouldReturnBadRequestOnNullSKU" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Put_ShouldReturnBadRequest_OnNullSKU" time="0.0006561" result="Fail">
        <failure>
          <message>Assert.IsType() Failure: Value is not the exact type
Expected: typeof(Microsoft.AspNetCore.Mvc.BadRequestResult)
Actual:   typeof(Microsoft.AspNetCore.Mvc.OkResult)</message>
          <stack-trace>   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Put_ShouldReturnBadRequest_OnNullSKU() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 347</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerPostShouldReturnInternalServerError" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Post_ShouldReturnInternalServerError_OnUnhandledException" time="0.0083164" result="Fail">
        <failure>
          <message>System.Exception : This is my dummy exception</message>
          <stack-trace>   at Moq.Behaviors.ThrowException.Execute(Invocation invocation) in /_/src/Moq/Behaviors/ThrowException.cs:line 64
   at Moq.MethodCall.ExecuteCore(Invocation invocation) in /_/src/Moq/MethodCall.cs:line 230
   at Moq.Setup.Execute(Invocation invocation) in /_/src/Moq/Setup.cs:line 144
   at Moq.FindAndExecuteMatchingSetup.Handle(Invocation invocation, Mock mock) in /_/src/Moq/Interception/InterceptionAspects.cs:line 263
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation) in /_/src/Moq/Interception/Mock.cs:line 17
   at Moq.CastleProxyFactory.Interceptor.Intercept(IInvocation underlying) in /_/src/Moq/Interception/CastleProxyFactory.cs:line 218
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IProductsServiceProxy.Create(Product entity)
   at HRBackendExercise.API.Controllers.ProductsController.Post(Product product) in /projects/challenge/HRBackendExercise.API/Controllers/ProductsController.cs:line 37
   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Post_ShouldReturnInternalServerError_OnUnhandledException() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 182</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerPutShouldReturnBadRequestOnZeroPrice" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Put_ShouldReturnBadRequest_OnPriceEqualsToZero" time="0.0007741" result="Fail">
        <failure>
          <message>Assert.IsType() Failure: Value is not the exact type
Expected: typeof(Microsoft.AspNetCore.Mvc.BadRequestResult)
Actual:   typeof(Microsoft.AspNetCore.Mvc.OkResult)</message>
          <stack-trace>   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Put_ShouldReturnBadRequest_OnPriceEqualsToZero() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 362</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerPutShouldReturnInternalServerError" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Put_ShouldReturnInternalServerError_OnUnhandledException" time="0.0021828" result="Fail">
        <failure>
          <message>System.Exception : This is my dummy exception.</message>
          <stack-trace>   at Moq.Behaviors.ThrowException.Execute(Invocation invocation) in /_/src/Moq/Behaviors/ThrowException.cs:line 64
   at Moq.MethodCall.ExecuteCore(Invocation invocation) in /_/src/Moq/MethodCall.cs:line 230
   at Moq.Setup.Execute(Invocation invocation) in /_/src/Moq/Setup.cs:line 144
   at Moq.FindAndExecuteMatchingSetup.Handle(Invocation invocation, Mock mock) in /_/src/Moq/Interception/InterceptionAspects.cs:line 263
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation) in /_/src/Moq/Interception/Mock.cs:line 17
   at Moq.CastleProxyFactory.Interceptor.Intercept(IInvocation underlying) in /_/src/Moq/Interception/CastleProxyFactory.cs:line 218
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IProductsServiceProxy.Update(Product entity)
   at HRBackendExercise.API.Controllers.ProductsController.Put(Product product) in /projects/challenge/HRBackendExercise.API/Controllers/ProductsController.cs:line 48
   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Put_ShouldReturnInternalServerError_OnUnhandledException() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 327</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerPutShouldBeHttpDecorated" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Put_ShouldHasAccordinglyDecorator" time="0.0006794" result="Fail">
        <failure>
          <message>Assert.Contains() Failure: Filter not matched in collection
Collection: []</message>
          <stack-trace>   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Put_ShouldHasAccordinglyDecorator() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 272</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerGetShouldReturnInternalServerError" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Get_ShouldReturnInternalServerError_OnUnhandledException" time="0.0014392" result="Fail">
        <failure>
          <message>System.Exception : This is my dummy exception</message>
          <stack-trace>   at Moq.Behaviors.ThrowException.Execute(Invocation invocation) in /_/src/Moq/Behaviors/ThrowException.cs:line 64
   at Moq.MethodCall.ExecuteCore(Invocation invocation) in /_/src/Moq/MethodCall.cs:line 230
   at Moq.Setup.Execute(Invocation invocation) in /_/src/Moq/Setup.cs:line 144
   at Moq.FindAndExecuteMatchingSetup.Handle(Invocation invocation, Mock mock) in /_/src/Moq/Interception/InterceptionAspects.cs:line 263
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation) in /_/src/Moq/Interception/Mock.cs:line 17
   at Moq.CastleProxyFactory.Interceptor.Intercept(IInvocation underlying) in /_/src/Moq/Interception/CastleProxyFactory.cs:line 218
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IProductsServiceProxy.GetById(Int32 id)
   at HRBackendExercise.API.Controllers.ProductsController.Get(Int32 id) in /projects/challenge/HRBackendExercise.API/Controllers/ProductsController.cs:line 20
   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Get_ShouldReturnInternalServerError_OnUnhandledException() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 92</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ControllerGetShouldBeHttpDecorated" type="HRBackendExercise.API.Tests.Hidden.ControllerTests" method="Get_ShouldHasAccordinglyDecorator" time="0.0087436" result="Fail">
        <failure>
          <message>Assert.Contains() Failure: Filter not matched in collection
Collection: []</message>
          <stack-trace>   at HRBackendExercise.API.Tests.Hidden.ControllerTests.Get_ShouldHasAccordinglyDecorator() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ControllerTests.cs:line 59</stack-trace>
        </failure>
        <traits />
      </test>
    </collection>
    <collection total="6" passed="0" failed="6" skipped="0" name="Test collection for HRBackendExercise.API.Tests.Hidden.ServiceTests" time="0.003">
      <test name="ServiceCreateShouldCreateARecord" type="HRBackendExercise.API.Tests.Hidden.ServiceTests" method="Create_ShouldAddARecord" time="0.0005692" result="Fail">
        <failure>
          <message>System.ArgumentNullException : Value cannot be null. (Parameter 'source')</message>
          <stack-trace>   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at HRBackendExercise.API.Services.ProductService.Create(Product entity) in /projects/challenge/HRBackendExercise.API/Services/ProductService.cs:line 12
   at HRBackendExercise.API.Tests.Hidden.ServiceTests.Create_ShouldAddARecord() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ServiceTests.cs:line 49</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ServiceUpdateShouldThrowArgumentBasedException" type="HRBackendExercise.API.Tests.Hidden.ServiceTests" method="Update_ShouldThrowArgumentBasedException_OnInvalidId" time="0.0007553" result="Fail">
        <failure>
          <message>Assert.StartsWith() Failure: String start does not match
String:         "Value cannot be null. (Parameter 'source'"···
Expected start: "Invalid entity."</message>
          <stack-trace>   at HRBackendExercise.API.Tests.Hidden.ServiceTests.Update_ShouldThrowArgumentBasedException_OnInvalidId() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ServiceTests.cs:line 93</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ServiceCreateShouldIgnoreInputId" type="HRBackendExercise.API.Tests.Hidden.ServiceTests" method="Create_ShouldIgnoreInputModelId" time="0.0004332" result="Fail">
        <failure>
          <message>System.ArgumentNullException : Value cannot be null. (Parameter 'source')</message>
          <stack-trace>   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at HRBackendExercise.API.Services.ProductService.Create(Product entity) in /projects/challenge/HRBackendExercise.API/Services/ProductService.cs:line 12
   at HRBackendExercise.API.Tests.Hidden.ServiceTests.Create_ShouldIgnoreInputModelId() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ServiceTests.cs:line 35</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ServiceCreateShouldAssignIncrementalIds" type="HRBackendExercise.API.Tests.Hidden.ServiceTests" method="Create_ShouldAssignIncrementalIds" time="0.0005261" result="Fail">
        <failure>
          <message>System.ArgumentNullException : Value cannot be null. (Parameter 'source')</message>
          <stack-trace>   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at HRBackendExercise.API.Services.ProductService.Create(Product entity) in /projects/challenge/HRBackendExercise.API/Services/ProductService.cs:line 12
   at HRBackendExercise.API.Tests.Hidden.ServiceTests.Create_ShouldAssignIncrementalIds() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ServiceTests.cs:line 16</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ServiceGetShouldReturnNullOnEmptyCollection" type="HRBackendExercise.API.Tests.Hidden.ServiceTests" method="Get_ShouldReturnNull_OnEmptyCollection" time="0.0004395" result="Fail">
        <failure>
          <message>System.ArgumentNullException : Value cannot be null. (Parameter 'source')</message>
          <stack-trace>   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean&amp; found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at HRBackendExercise.API.Services.ProductService.GetById(Int32 id) in /projects/challenge/HRBackendExercise.API/Services/ProductService.cs:line 27
   at HRBackendExercise.API.Tests.Hidden.ServiceTests.Get_ShouldReturnNull_OnEmptyCollection() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ServiceTests.cs:line 64</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="ServiceGetShouldReturnNullOnInvalidId" type="HRBackendExercise.API.Tests.Hidden.ServiceTests" method="Get_ShouldReturnNull_OnInvalidId" time="0.0003924" result="Fail">
        <failure>
          <message>System.ArgumentNullException : Value cannot be null. (Parameter 'source')</message>
          <stack-trace>   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at HRBackendExercise.API.Services.ProductService.Create(Product entity) in /projects/challenge/HRBackendExercise.API/Services/ProductService.cs:line 12
   at HRBackendExercise.API.Tests.Hidden.ServiceTests.Get_ShouldReturnNull_OnInvalidId() in /projects/challenge/HRBackendExercise.API.Tests/Hidden/ServiceTests.cs:line 77</stack-trace>
        </failure>
        <traits />
      </test>
    </collection>
  </assembly>
</assemblies>